# Git repositories to sync by default
declare -a default_repos=("$HOME/org"
                          "$HOME/blog"
                          "$HOME/journal"
                          "$HOME/wiki"
                          "$HOME/lib/spacemacs"
                          "$HOME/lib/thus-utils"
                          "$HOME/.config/termrc"
                          "$HOME/.vim"
                          "$HOME/.task/taskrc"
                          "$HOME/.config/emacs"
                          "$HOME/.timetrap/formatters"
                          "$HOME/.config/i3/i3rc"
                          "$HOME/Documents/home/SOP"
                          "$HOME/texmf")
